version: '3'
services:
  malunpacker:
    image: malunpacker:latest
    cpus: 2.0
    logging:
      options:
        max-size: 50m
    volumes:
      - etc:/etc/malunpacker
      - quarantine:/opt/quarantine
    ports:
      - "10055:10055"
    #restart: always

volumes:
  etc:
  quarantine:
